### PR TITLE
View separation

### PR DESCRIPTION
**Pull request by zbendas**
Per #1, I've tried my hand at disentangling the view/presentation layers from the actual logic inside of the various classes.

This new `View` class gives a host of bespoke static methods that they can use to hook into specific templates, generate the desired string, and then feed that string back into `View.render()` to be output. Of course, `View.render()` can be used on its own as a simple wrapper for `builtins.print`. This wrapper would allow any very broad-stroke transformations to be applied in one place. And new template preparations could be concocted as-needed using `View.prepare_template()`.

Additionally, I separated the user input from raw calls into a similar wrapper, found in `user_input.py` and the `UserInput` class. The only specific method supplied here is `get_pick_up_input()`, which determines whether a user wants to draw from the deck or pick up a discarded card, returning the result to the caller.

Included are tests for these methods, comparing them against expected strings and testing how often they are called and with what arguments, to make sure that their raw behavior (i.e, calls to `builtins.print` and `builtins.input` is preserved).

As one last piece of clean-up, I took care of the `TODO` that was related to `console_config.py` and just shuffled the `colorama` initialization into `play.py` (specifically `Play.init()`), as it seemed like a sensible enough place to do so.

### CODE REVIEW

**Comment by zbendas** [comment]
It looks like this branch decreased percent code coverage just a bit, but I think that's due to the removal of a few lines that were covered, and leaving a few that weren't.

I'm writing further tests to fix this in a separate branch for now, but would be happy to commit those changes to this branch, to boost coverage back up.

**Comment by OrderAndCh4oS** [comment]
Taking a look now, it all sounds spot on. Thanks again. Sorry for the delay getting back to you, I've not yet worked out where PR notifications are displayed other than going straight to the project on GitHub.

**Comment by OrderAndCh4oS** [comment]
Looking good. I wouldn't worry too much about the drop in percentage, we're not looking for 100% coverage.

I've moved the `view` and `user_input` to a new package called `ui`. This broke a test that was relying on importing sleep from rummy.game.view. I've removed that test, I don't think it's needed.

Nice work wrapping the print and inputs it makes much more sense to do this. The next step that I'm looking into now is removing all the calls to `View.render()` from the methods. I want to have the render and the user_inputs called in only one place and have all the methods return strings. This will make testing them much easier. 

I plan to make some kind of manager that will handle outputting all the prints and inputs. I think the `Play` class kind of does this but it needs refactoring, as will many of the methods that are doing too many things. 

Thanks again, superb work. 

Let me know what you're up to if you're still working on some bits and pieces, this next step will need to alter a lot.

**Comment by OrderAndCh4oS** [comment]
I've created a new branch https://github.com/sarcoma/Python-Rummy/tree/action_seperation that further separates out the rendering of views. It's not there yet, but it's all I have time to do right now. It's broken some of the tests, I can go over and update them though at some point.

I've tried to create methods in AI and Human that either accept input or produce output. Eventually, the output will be returned to the caller and the caller can decide how and when to render it. 

Also, I've reworked the menu system for game controls. It now uses ActionCollection to group Actions together. At the moment Actions takes the acceptable user inputs and the action label (further down the line it may be possible to bind to a function too) and returns the user input. 

I'll have some more time on this later and/or tomorrow.

Thanks for the work you've put in it's really appreciated!

**Comment by zbendas** [comment]
Of course! More than happy to help out.

I'll take a look at fixing the broken tests, and let you square away the new interactions system. I'll submit the next round of those changes as a PR to the `action_separation` branch, once I've got that done.

If there's anything else I can work on, let me know!

**Comment by OrderAndCh4oS** [comment]
I think I've broken most of them, sorry about that, I can look at fixing them. I'm not sure I've made real gains with the changes. It feels a bit cleaner but there is something lacking. I want to get to a point where there is a single layer handling rendering the views. It's a step closer to that, but it needs some thought about how to actually implement it.

**Pull request merged**
