### PR TITLE
Allow running as a module

### PR DESCRIPTION
**Pull request by alxwrd**
happy hacktoberfest :wave: :jack_o_lantern: :fallen_leaf: !

This add's a `__main__.py` file to allow running `rummy` without installing.

```shell
git clone https://github.com/sarcoma/Python-Rummy.git
cd Python-Rummy
pip install -r requirements.txt
python -m rummy
```

To get this to work I had to load `constants` from `rummy`, but all tests are still passing locally with this change.

Let me know if you also want this documented in the README.

### CODE REVIEW

**Comment by OrderAndCh4oS** [comment]
Ha, thanks so much, I wondered what I needed to do for that to work again!

I'll take a look and make sure it works this end.

**Comment by OrderAndCh4oS** [comment]
Ah, I see what I did, I have a file called command_line.py for running while testing. I'll just see if there was a reason I didn't use __main__.py. I might have had some trouble with packaging it for pip.

**Comment by OrderAndCh4oS** [comment]
All good, merged, thanks again. There's now no need for the command_line.py the contents can be moved straight into __main__.py.

**Comment by alxwrd** [comment]
@sarcoma fantastic! Maybe worth raising an issue for moving `command_line.py` to `__main__.py`? Could be a good one for #hacktoberfest.

**Comment by OrderAndCh4oS** [comment]
@alxwrd Will do. I realised that command_line.py is used in setup.py as the entry point, that'd need updating too. I'll create the issue now.

**Pull request merged**
