### PR TITLE
Create tests for most classes

### PR DESCRIPTION
**Pull request by zbendas**
Per #4, I've written tests to cover the majority of the underlying code base, save `ai.py`.

The more directly-executable code, such as in `play.py` doesn't have any tests written for it yet either. I figured I'd submit this batch and then work to write tests for `play.py` and `ai.py`.

This is my first time really delving this far into tests, so please let me know if there's anything I can improve or change for these, or future tests. Of note, I did find myself introducing a new dependency (at least for the testing environment) by way of `pytest-mock`, as this helped immensely in having a `pytest` wrapper for Python's `mock` functions.

Included are a few (of what I believe to be) bug fixes or prunings of unused code. I also restructured the `tests` folder.

This is also my first (real) PR, so please let me know if there's something I can improve on!

### CODE REVIEW

**Comment by OrderAndCh4oS** [comment]
Wow, thanks so much, this is great work. Sorry for the delay in getting back to you. There seems to be an issue with passing the remote tests. I'll take a look to see where it's at. 

Thanks again.

**Comment by zbendas** [comment]
No worries! It looked to me like a bug I introduced by mocking the wrong version of `random.choice` in the `test_ai.py`. I've corrected that as of 29974a1, I believe.

**Comment by OrderAndCh4oS** [comment]
Really I can't thank you enough this is really great stuff. `pytest-mock` is fantastic, I'll have to read up about that. 

I've not got any tips to offer, you've totally nailed it. Awesome PR!

**Comment by OrderAndCh4oS** [comment]
All merged!

**Pull request merged**
